# https://alacritty.org/config-alacritty.html

general.import = [
  ".themes/themes/monokai_pro.toml"
]

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
  {    key = "Return",  mods = "Control|Shift",    action = "SpawnNewInstance"  }
]
